version: "3.8"
services:
  anvil:
    build:
      context: ./anvil-service
    container_name: anvil-service
    env_file:
      - '../config/.env'
    
  anvil-proxy:
    build:
      context: ./anvil-proxy-service
    container_name: anvil-proxy-service
    ports:
     - 9000:9000 
    depends_on:
      - anvil

  launcher:
    build:
      context: ./launcher-service
    container_name: launcher-service
    ports:
      - "8888:8888"
    depends_on:
      - anvil
    volumes:
      - ../config/src:/home/h4ck3r/chall/src:ro
      - ../config/foundry.toml:/home/h4ck3r/chall/foundry.toml:ro
    environment:
      - RPC_URL=http://127.0.0.1:9000
    env_file:
      - '../config/.env'
    